import Head from 'next/head';
import Image from 'next/image';
import { initiateCheckout } from '../lib/payments';

import products from '../products.json';
import styles from '../styles/Home.module.css';

export default function Home() {
    const renderProduct = ({ id, title, description, image, price }) => {
        return (
            <li className={styles.card} key={id}>
                <a href="https://nextjs.org/docs">
                    <Image
                        src={image}
                        alt="Space Jelly Tshirt"
                        width="100%"
                        height="100%"
                    />
                    <h2>{title}</h2>
                    <p>$ {price}</p>
                    <p>{description}</p>
                </a>
                <p>
                    <button
                        className={styles.button}
                        onClick={() =>
                            initiateCheckout({
                                lineItems: [
                                    {
                                        price: id,
                                        quantity: 1,
                                    },
                                ],
                            })
                        }
                    >
                        Buy now!
                    </button>
                </p>
            </li>
        );
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Space Jelly Shop</h1>

                <p className={styles.description}>
                    The best space jellyfish swag on the web!
                </p>

                <ul className={styles.grid}>{products.map(renderProduct)}</ul>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://javiergomezve.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>javiergomezve</span>
                </a>
            </footer>
        </div>
    );
}
