import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Space Jelly Shop</h1>

                <p className={styles.description}>
                    The best space jellyfish swag on the web!
                </p>

                <ul className={styles.grid}>
                    <li className={styles.card}>
                        <a href="https://nextjs.org/docs">
                            <img
                                src="/images/spacejelly-tshirt.png"
                                alt="Space Jelly Tshirt"
                            />
                            <h2>Space Jelly Tshirt</h2>
                            <p>$20.00</p>
                            <p>
                                Bring Cosmo the space Jellyfish to your wardrobe
                                with this high quality tshirt.
                            </p>
                        </a>
                    </li>

                    <li className={styles.card}>
                        <a href="https://nextjs.org/learn">
                            <img
                                src="/images/spacejelly-stickers.png"
                                alt="Space Jelly Stickers"
                            />
                            <h2>Space Jelly Stickers</h2>
                            <p>$10.00</p>
                            <p>
                                Add some flare to your laptop with a sticker of
                                Cosmo the Space Jellyfish.
                            </p>
                        </a>
                    </li>

                    <li className={styles.card}>
                        <a href="https://github.com/vercel/next.js/tree/master/examples">
                            <img
                                src="/images/spacejelly-combo.png"
                                alt="Space Jelly Combo"
                            />
                            <h2>Space Jelly Combo</h2>
                            <p>$25.00</p>
                            <p>
                                Show your love for Cosmo with a tshirt and
                                sticker combo pack!
                            </p>
                        </a>
                    </li>
                </ul>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://javiergomezve.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>javiergomezve</span>
                </a>
            </footer>
        </div>
    );
}
